// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RSSI_webAPI.Data;

#nullable disable

namespace RSSI_webAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RSSI_webAPI.Models.SupervisedDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Bt")
                        .HasColumnType("real");

                    b.Property<float>("BxGSM")
                        .HasColumnType("real");

                    b.Property<float>("ByGSM")
                        .HasColumnType("real");

                    b.Property<float>("BzGSM")
                        .HasColumnType("real");

                    b.Property<float>("Declination")
                        .HasColumnType("real");

                    b.Property<float>("East")
                        .HasColumnType("real");

                    b.Property<float>("Horizontal")
                        .HasColumnType("real");

                    b.Property<float>("Inclination")
                        .HasColumnType("real");

                    b.Property<float>("Intensity")
                        .HasColumnType("real");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<float>("North")
                        .HasColumnType("real");

                    b.Property<float>("Vertical")
                        .HasColumnType("real");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ReconnectionRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
